// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solid.Data;

namespace Solid.Migrations
{
    [DbContext(typeof(TypetalkDataContext))]
    [Migration("20181024021140_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Solid.Data.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Solid.Data.Entities.Like", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountId");

                    b.Property<string>("PostId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("Solid.Data.Entities.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Message");

                    b.Property<string>("PostId");

                    b.Property<string>("QueryCacheId");

                    b.Property<string>("TopicId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("QueryCacheId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Solid.Data.Entities.QueryCache", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FromDate");

                    b.Property<string>("SpaceKey");

                    b.Property<DateTime>("ToDate");

                    b.Property<string>("TopicId");

                    b.HasKey("Id");

                    b.ToTable("QueryCache");
                });

            modelBuilder.Entity("Solid.Data.Entities.Like", b =>
                {
                    b.HasOne("Solid.Data.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Solid.Data.Entities.Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("Solid.Data.Entities.Post", b =>
                {
                    b.HasOne("Solid.Data.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Solid.Data.Entities.QueryCache")
                        .WithMany("Posts")
                        .HasForeignKey("QueryCacheId");
                });
#pragma warning restore 612, 618
        }
    }
}
